---
# tasks file for roles/nginx-proxy selinux

- name: nginx | selinux allow network connect
  become: true
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

# This may not work if the port already has a different setype assigned to it
- name: nginx | stream selinux ports
  become: true
  seport:
    ports: "{{ item.port }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items: "{{ nginx_proxy_streams }}"

# /etc/selinux/targeted/contexts/files/file_contexts is missing
# /var/cache/nginx(/.*)? so Nginx may not be able to modify the cache
- name: nginx | selinux cache context policy
  become: true
  sefcontext:
    target: >-
      {{ nginx_proxy_cache_parent_path | regex_replace('\\/$', '') }}(/.*)?
    setype: httpd_cache_t
    state: present

- name: nginx | restore cache context
  become: true
  command: >-
    /usr/sbin/restorecon -R -v
    {{ ansible_check_mode | ternary('-n', '') }}
    {{ nginx_proxy_cache_parent_path }}
  register: result
  check_mode: false
  changed_when: 'result.stdout != ""'
